services:
  postgres:
    image: postgres:16
    container_name: debts_pg
    environment:
      POSTGRES_USER: debts
      POSTGRES_PASSWORD: debts
      POSTGRES_DB: debtsdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: debts_redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
